[runner]
fastReruns = false
[server]
headless = true
runOnSave = true
port = 5001
enableCORS = false
enableXsrfProtection=false
[theme]
primaryColor="#dca5ce"
backgroundColor="#0e1117"
secondaryBackgroundColor="#31333f"
textColor="#fafafa"
font="sans serif"

